// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using __tarea7.Data;

namespace __tarea7.Migrations
{
    [DbContext(typeof(vacunadosDbContext))]
    [Migration("20210311191906_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("__tarea7.Data.vacunados", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis1")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis2")
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("provincia")
                        .HasColumnType("TEXT");

                    b.Property<long>("telefono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipoVacuna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "h",
                            apellido = "ramirez",
                            nombre = "Laptop",
                            telefono = 10L,
                            tipoVacuna = "This is a best gaming laptop"
                        },
                        new
                        {
                            Id = "d",
                            apellido = "ramirez",
                            nombre = "Microsoft Office",
                            telefono = 50L,
                            tipoVacuna = "This is a Office Application"
                        },
                        new
                        {
                            Id = "t",
                            apellido = "ramirez",
                            nombre = "Lazer Mouse",
                            telefono = 20L,
                            tipoVacuna = "The mouse that works on all surface"
                        },
                        new
                        {
                            Id = "g",
                            apellido = "ramirez",
                            fecahDosis1 = "f",
                            fecahDosis2 = "f",
                            fechaNacimiento = "a",
                            nombre = "USB Storage",
                            provincia = "c",
                            telefono = 20L,
                            tipoVacuna = "To store 256GB of data"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
