// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using __tarea7.Data;

namespace __tarea7.Migrations
{
    [DbContext(typeof(vacunadosDbContext))]
    partial class vacunadosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("_Tarea7.Data.vacunados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis1")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis2")
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("provincia")
                        .HasColumnType("TEXT");

                    b.Property<long>("telefono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipoVacuna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            apellido = "ramirez",
                            nombre = "Laptop",
                            telefono = 10L,
                            tipoVacuna = "This is a best gaming laptop"
                        },
                        new
                        {
                            Id = 1002,
                            apellido = "ramirez",
                            nombre = "Microsoft Office",
                            telefono = 50L,
                            tipoVacuna = "This is a Office Application"
                        },
                        new
                        {
                            Id = 1003,
                            apellido = "ramirez",
                            nombre = "Lazer Mouse",
                            telefono = 20L,
                            tipoVacuna = "The mouse that works on all surface"
                        },
                        new
                        {
                            Id = 1004,
                            apellido = "ramirez",
                            fecahDosis1 = "f",
                            fecahDosis2 = "f",
                            fechaNacimiento = "a",
                            nombre = "USB Storage",
                            provincia = "c",
                            telefono = 20L,
                            tipoVacuna = "To store 256GB of data"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
